### ISSUE TITLE
Using CSS Custom Properties to Write Better CSS

### ISSUE THREAD

**Issue by wellington-damasio** [wellington-damasio/github-blog_issues#2]
I. Use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) to write theme variables
This is a very simple trick that helps you apply the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) concept to your CSS stylesheets.

We can set up "style variables" for further use during our development

```css
:root {
  /* Colors */
  --base-color: #f1f1f1;
  --primary-color: #222;
  --btn-primary: #00b4d8;
  --accent-color: #f77f00;
  
  /* Typography */
  --fz-sm: 0.85rem;
  --fz-base: 1rem;
  --fz-md: 1.2rem;
  --fz-lg: 1.5rem;
  --fz-xl: 2rem;
  
  /* Spacing */
  --p-sm: 1rem; /* p == padding */
  --p-md: 1.7rem;
  --p-lg: 2.1rem;
  
  --m-sm: 1rem; /* m == margin */
  --m-md: 1.5rem;
  --m-lg: 2rem;
}

```

After setting up our styles variables in the `:root` we can use them throughout our CSS by using var(--variable-name)
